### ISSUE TITLE
Very High CPU usage when midi device is selected

### ISSUE THREAD

**Issue by rhrhunter** [rhrhunter/vcv-robrichards#3]
See: https://github.com/VCVRack/Rack/issues/1646

The fix to Rack (v1) is relatively easy (see https://github.com/VCVRack/Rack/pull/1647), but can't be merged upstream because of version incompatibility which is weighed higher than performance improvements. The justification to not fix is because this is fixed in the next version of Rack (v2).

**Comment by nickgerace** [comment]
Bummer. This was a good fix. Good thing it was caught!
